Repository wonsik3686/wine, pull requests merged in 2024-09, with the labels that each got.

#73 Chore/prettier
  .prettierrc
  .prettierrc.js
Labels: 버그, 수정, 세팅

#62 feature/24 공통컴포넌트 프로그레스바 추가
  components/common/RatingProgressbar.tsx
Labels: 새 기능

#66 Feature/13,22 공통컴포넌트 (가격,별점)박스
  components/common/Boxs.tsx
  public/svg/star.svg
Labels: 새 기능

#65 Feature/26 공통컴포넌트 dropdown 추가
  app/favicon.ico
  app/globals.css
  components/common/dropdown/Dropdown.module.css
  components/common/dropdown/Dropdown.tsx
  public/dropdown_arrow_down.png
  public/dropdown_arrow_up.png
  public/next.svg
  public/vercel.svg
Labels: 새 기능

#71 Feature/16 공통컴포넌트 input 추가
  .prettierrc
  .vscode/settings.json
  components/common/Input.tsx
  components/common/SearchInput.tsx
  components/common/TextArea.tsx
  public/icons/iconSearch.svg
  types/common.types.ts
Labels: 새 기능

#75 Feature/36 공통 컴포넌트 값 표기 슬라이더 구현
  .prettierrc.js
  app/globals.css
  components/common/Slider.tsx
  package-lock.json
  package.json
Labels: 새 기능

#72 Feature/8 공통컴포넌트 별점컴포넌트 추가
  components/common/StarRating.tsx
  public/images/star_active.svg
  public/images/star_inactive.svg
Labels: 새 기능

#76 Feature/3 공통 컴포넌트 DoubleSlider 추가
  components/common/DoubleSlider.tsx
Labels: 새 기능

#77 Feature/12 공통컴포넌트 칩컴포넌트 추가
  components/common/Chip.tsx
  package-lock.json
Labels: 새 기능

#78 Feature/35-공통-컴포넌트-헤더
  app/page.tsx
  components/common/header.tsx
  public/icons/wineWhiteLogo-s.svg
  public/svg/star.svg
  tailwind.config.ts
Labels: 새 기능

#81 Feature/37 공통컴포넌트 원형 프로필 사진
  app/page.tsx
  components/common/AddProfile.tsx
  components/common/Header.tsx
  components/common/Profile.tsx
  public/icons/defaultProfile.svg
  public/svg/addProfile.svg
Labels: 새 기능

#83 feature/style: ESLint 관련 수정 - 칩, 별점, 드롭다운
  components/common/Chip.tsx
  components/common/StarRating.tsx
  components/common/dropdown/Dropdown.tsx
Labels: 수정

#84 Feature: Slider/DoubleSlider ESLint 관련 수정
  app/layout.tsx
  components/common/DoubleSlider.tsx
  components/common/Slider.tsx
Labels: 수정

#87 style: ESLint 오류 수정
  components/common/Boxes.tsx
  public/icons/star.svg
Labels: 수정

#86 Feature/styles:ESLint 신윤하
  app/page.tsx
  components/common/Profile.tsx
Labels: 수정

#90 feat: dev서버 테스트경로 생성
  app/test/page.tsx
  components/common/Boxes.tsx
  public/icons/star.svg
Labels: 기타

#92 feat: 공통컴포넌트 Button 스타일 추가 #91
  components/common/Button.tsx
Labels: 새 기능

#93 Feature/19 랜딩페이지 추가
  app/layout.tsx
  app/page.tsx
  components/common/Header.tsx
  public/images/landing/landingIntro1.png
  public/images/landing/landingIntro2.png
  public/images/landing/landingIntro3.png
  public/images/landing/landing_sm_01.png
  public/images/landing/landing_sm_02.png
  public/images/landing/landing_sm_03.png
  public/images/landing/landing_sm_04.png
  types/common.types.ts
Labels: 새 기능

#95 Fix/94 주요기능 button 비활성화 스타일 추가
  app/test/page.tsx
  components/common/Button.tsx
Labels: 수정

#101 feat: 별점 컴포넌트 small사이즈 추가 및 테스트 페이지 추가
  app/test/page.tsx
  components/common/StarRating.tsx
Labels: 새 기능

#105 design: 칩 컴포넌트 스타일 변경 및 색상변수, 테스트페이지 추가
  app/test/page.tsx
  components/common/Chip.tsx
  tailwind.config.ts
Labels: 수정

#102 Feature/29 주요기능 와인 등록하기 모달 추가
  app/test/page.tsx
  components/common/dropdown/Dropdown.tsx
  components/modal/AddWineModal.tsx
  components/modal/Modal.module.css
  components/modal/Modal.tsx
  components/modal/WineImageInput.tsx
  public/icons/icon_photo.png
Labels: 새 기능

#104 Feature/38: 와인 목록 페이지 UI 일부 구현
  app/globals.css
  app/layout.tsx
  app/wines/page.tsx
  assets/icons/iconArrowRight.svg
  assets/icons/iconFilter.svg
  components/common/Chip.tsx
  components/common/DoubleSlider.tsx
  components/common/RadioButton.tsx
  components/common/SearchInput.tsx
  components/common/StarRating.tsx
  components/wines/FilteringModal.tsx
  components/wines/FilteringOpenButton.tsx
  components/wines/MonthlyWineCard.tsx
  components/wines/MonthlyWineSection.tsx
  components/wines/RatingSelector.tsx
  components/wines/WineCard.tsx
  components/wines/WineCardGallery.tsx
  components/wines/WineSection.tsx
  package-lock.json
  package.json
  postcss.config.mjs
Labels: 도큐먼테이션, 새 기능, 수정

#103 Feature/20 와인상세페이지 와인정보컴포넌트 추가
  app/wines/[id]/layout.tsx
  app/wines/[id]/page.tsx
  components/common/Header.tsx
  components/wines/WineDetailCard.tsx
  next.config.mjs
  tailwind.config.ts
Labels: 새 기능

#108 Feature/55 주요기능 로그인 페이지
  api/_axiosInstance.ts
  app/auth/signIn/page.tsx
  components/common/Input.tsx
  public/icons/wineBlackLogo-l.svg
  store/useAuthStore.ts
  types/user.types.ts
Labels: 새 기능

#106 Feature/21 와인상세페이지 와인상세별점 추가
  app/test/page.tsx
  app/wines/[id]/page.tsx
  components/common/Button.tsx
  components/common/RatingProgressbar.tsx
  components/wines/WineReviewsRating.tsx
  tailwind.config.ts
Labels: 새 기능

#110 Feature/107 주요기능 와인상세페이지 리뷰목록 추가
  app/wines/[id]/page.tsx
  components/common/Chip.tsx
  components/common/ChipSwiper.tsx
  components/common/dropdown/Dropdown.tsx
  components/wines/WineReviewList.tsx
  components/wines/WineReviewsRating.tsx
  components/wines/WineTasteSlider.tsx
  package-lock.json
  package.json
  public/icons/iconArrowDown.svg
  public/icons/iconArrowUp.svg
  public/icons/iconDot.png
  public/icons/iconHeart.png
  types/review.types.ts
  types/wine.types.ts
  utils/dateTimeUtils/FormatDistanceToNow.ts
  utils/translate/TranslateAromaToKorean.ts
Labels: 새 기능

#115 rename: app 폴더 구조 변경
  app/(auth)/login/page.tsx
  app/(home)/layout.tsx
  app/(home)/myprofile/page.tsx
  app/(home)/page.tsx
  app/(home)/test/page.tsx
  app/(home)/wines/[id]/layout.tsx
  app/(home)/wines/[id]/page.tsx
  app/(home)/wines/page.tsx
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  app/signup/page.tsx
  components/common/Header.tsx
  components/common/StarRating.tsx
  components/modal/AddWineModal.tsx
  components/modal/WineImageInput.tsx
  components/wines/WineReviewList.tsx
  components/wines/WineReviewsRating.tsx
  next.config.mjs
  providers/RootHeader.tsx
  tailwind.config.ts
Labels: 리팩토링

#118 Feature/33 주요기능 삭제하기모달 추가
  app/(home)/test/page.tsx
  components/modal/DeleteModal.tsx
Labels: 새 기능

#123 Feature/121 주요기능 모달 POST 요청 추가
  api/reviews.api.ts
  api/wines.api.ts
  app/(home)/test/page.tsx
  components/common/Slider.tsx
  components/common/StarRating.tsx
  components/modal/AddWineModal.tsx
  components/modal/Modal.tsx
  components/modal/WineImageInput.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  components/modal/reviewmodal/TagSelector.tsx
  components/modal/reviewmodal/TasteSlider.tsx
  queries/addwine.queries.ts
  store/useReviewModalStore.ts
Labels: 새 기능

#126 Feature/23 와인상세페이지 리뷰남기기 모달 추가
  api/reviews.api.ts
  app/(home)/wines/[id]/page.tsx
  components/modal/DeleteModal.tsx
  components/wines/WineReviewList.tsx
  components/wines/WineReviewsRating.tsx
  hooks/modal/useReviewModal.tsx
  hooks/reviews.controller.tsx
  hooks/reviews/useDeleteReview.tsx
  hooks/useAuth.ts
  hooks/wines/useLikeReview.tsx
  package-lock.json
  package.json
  providers/query.tsx
  public/icons/iconHeart.svg
  public/icons/iconHeartFilled.svg
  queries/reviews.queries.ts
  queries/wines.queries.ts
  store/useAuthStore.ts
  types/dto/request/review.request.types.ts
  types/dto/response/review.response.types.ts
Labels: 도큐먼테이션, 새 기능

#127 Feature/32 주요기능 와인리뷰수정하기모달 추가
  api/reviews.api.ts
  app/(home)/test/page.tsx
  app/(home)/wines/[id]/page.tsx
  components/modal/AddWineModal.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  components/modal/reviewmodal/ReviewInput.tsx
  queries/addwine.queries.ts
  queries/reviews.queries.ts
  store/useReviewModalStore.ts
  types/dto/request/review.request.types.ts
  types/dto/response/review.response.types.ts
  utils/convert/convertToAroma.ts
Labels: 새 기능

#129 fix: 와인상세페이지 와인등록모달 버그 수정 #32
  app/(home)/test/page.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
Labels: 버그

#113 fix: input 컴포넌트 ClassNameProps 추가
  components/common/Input.tsx
Labels: 리팩토링

#117 Feature/116 API-user/imageUpload 구현 및 user type 정의 파일 작성
  api/imageUpload.api.ts
  api/users.api.ts
  types/user.types.ts
Labels: 새 기능

#138 Feature/109 주요기능 와인상세페이지 오류 처리 및 나머지 기능 추가
  app/(home)/wines/[id]/components/WineDetail.tsx
  app/(home)/wines/[id]/page.tsx
  components/common/RatingProgressbar.tsx
  components/common/dropdown/Dropdown.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  components/modal/reviewmodal/ReviewInput.tsx
  components/modal/reviewmodal/TagSelector.tsx
  components/modal/reviewmodal/TasteSlider.tsx
  components/wines/NoReviewContent.tsx
  components/wines/WineReviewList.tsx
  components/wines/WineReviewsRating.tsx
  public/icons/iconNoContent.svg
  queries/reviews.queries.ts
  store/useReviewModalStore.ts
Labels: 버그, 새 기능, 리팩토링

#119 Feature/유저 프로필 수정 컴포넌트 #112 #40
  app/(auth)/login/page.tsx
  app/(home)/myprofile/page.tsx
  components/auth/Profile.tsx
  components/auth/ProfileUpload.tsx
  components/common/Button.tsx
  components/common/Input.tsx
  public/icons/photo.svg
Labels: 새 기능

#133 Feature/34 추가기능 확인모달 추가
  app/(home)/test/page.tsx
  components/modal/ConfirmModal.tsx
Labels: 새 기능

#124 Feature/55 주요기능 로그인 페이지
  app/(auth)/login/page.tsx
Labels: 수정

#140 Feature/120 유저프로필페이지 탭메뉴
  api/imageUpload.api.ts
  api/users.api.ts
  api/wines.api.ts
  app/(home)/myprofile/page.tsx
  app/(home)/test/page.tsx
  app/layout.tsx
  components/auth/Profile.tsx
  components/auth/ProfileUpload.tsx
  components/auth/UserTapMenu.tsx
  components/modal/AddWineModal.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  package-lock.json
  package.json
  public/icons/kebab.svg
  store/useUserStore.ts
  types/user.types.ts
Labels: 새 기능

#142 Feature/139 추가기능 랜딩페이지 애니메이션 추가
  app/(home)/page.module.css
  app/(home)/page.tsx
  app/favicon.ico
  app/globals.css
  package-lock.json
  package.json
  public/images/landing/filter.png
  public/images/landing/filter_01.png
  public/images/landing/filter_02.png
  public/images/landing/landing_logo_purple.png
  public/images/landing/landing_wine_detail_01.png
  public/images/landing/landing_wine_detail_02.png
  public/images/landing/landing_wine_filter.png
  public/images/landing/monthly_wine1.png
  public/images/landing/monthly_wine2.png
  public/images/landing/monthly_wine3.png
  public/images/landing/monthly_wine4.png
  public/images/landing/monthly_wine5.png
  public/images/landing/recommended_card.png
Labels: 새 기능

#141 Feature/56 주요기능 회원가입 페이지
  api/_axiosInstance.ts
  api/auth.api.ts
  app/(auth)/login/page.tsx
  app/(auth)/register/page.tsx
  app/layout.tsx
  components/common/Chip.tsx
  components/common/DoubleSlider.tsx
  components/common/Header.tsx
  components/common/SearchInput.tsx
  components/common/dropdown/Dropdown.tsx
  components/wines/WineReviewList.tsx
  hooks/wines/useLikeReview.tsx
  providers/auth.tsx
  store/useAuthStore.ts
Labels: 새 기능

#145 hotfix: 인증관련 에러 처리
  api/_axiosInstance.ts
Labels: 버그

#143 Feature/109 주요기능 와인상세페이지 오류 처리 및 나머지 기능 추가
  api/users.api.ts
  app/(auth)/register/page.tsx
  app/(home)/error.tsx
  app/(home)/not-found.tsx
  app/(home)/wines/[id]/layout.tsx
  app/(home)/wines/[id]/page.tsx
  app/favicon.ico
  app/layout.tsx
  components/auth/Profile.tsx
  components/auth/ProfileUpload.tsx
  public/icons/icon.svg
  public/images/notFound/not_found.png
  queries/reviews.queries.ts
  queries/users.queries.ts
  store/useAuthStore.ts
  store/useUserStore.ts
Labels: 버그, 새 기능

#148 design: Chip 디자인 수정
  components/common/Chip.tsx
Labels: 수정

#150 Fix/149 랜딩페이지 모바일css 수정
  app/(home)/page.tsx
  app/layout.tsx
  components/common/dropdown/Dropdown.tsx
  components/modal/AddWineModal.tsx
  components/wines/WineSection.tsx
  public/thumbnail.png
Labels: 수정

#151 Feature/147 와인상세페이지 추가기능 추가
  api/_axiosInstance.ts
  app/(auth)/error.tsx
  app/(auth)/login/layout.tsx
  app/(auth)/login/page.tsx
  app/(home)/layout.tsx
  app/(home)/wines/[id]/components/ShareButtons.tsx
  app/(home)/wines/[id]/components/WineDetail.tsx
  app/(home)/wines/[id]/components/skeletons/WineDetailCardSkeleton.tsx
  app/(home)/wines/[id]/components/skeletons/WineDetailSkeleton.tsx
  app/(home)/wines/[id]/components/skeletons/WineReviewsSkeleton.tsx
  app/(home)/wines/[id]/loading.tsx
  app/(home)/wines/[id]/page.tsx
  app/layout.tsx
  components/common/Header.tsx
  components/modal/ConfirmModal.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  components/wines/NoReviewContent.tsx
  components/wines/WineDetailCard.tsx
  components/wines/WineReviewList.tsx
  hooks/modal/useLoginConfirmModal.tsx
  hooks/share/useFacebookShare.tsx
  hooks/share/useKakaoShare.tsx
  hooks/share/useXShare.tsx
  package-lock.json
  package.json
  public/icons/iconFacebook.svg
  public/icons/iconKakao.svg
  public/icons/iconShare.svg
  public/icons/iconTwitterX.svg
  queries/reviews.queries.ts
  queries/wines.queries.ts
  utils/script/KakaoScript.tsx
Labels: 버그, 새 기능, 리팩토링

#152 feat: 간편 회원가입 구글 간편로그인 구현 #57
  .env
  api/auth.api.ts
  app/(auth)/login/page.tsx
  app/(home)/header-wrapper.tsx
  app/(home)/layout.tsx
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  components/common/Header.tsx
  next.config.mjs
  package-lock.json
  package.json
  providers/auth.tsx
  store/useAuthStore.ts
  types/next-auth.d.ts
Labels: 새 기능

#154 feat: 모달 애니메이션 추가
  components/modal/Modal.module.css
  components/modal/Modal.tsx
Labels: 새 기능

#153 Feature/135 추가기능 모달인풋 에러메시지 추가
  components/modal/AddWineModal.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  components/modal/reviewmodal/ReviewInput.tsx
  components/modal/reviewmodal/TagSelector.tsx
Labels: 새 기능

#155 Feature/57 주요기능 간편 회원가입
  .env
  app/(auth)/login/page.tsx
  app/(home)/header-wrapper.tsx
  app/(home)/layout.tsx
  app/api/auth/[...nextauth]/route.ts
  app/api/kakaoLogin/route.ts
  next.config.mjs
  store/useAuthStore.ts
Labels: 새 기능

#158 hotfix/ env 수정
  .env
Labels: 버그

#161 fix: nextauth 의 NEXTAUTH_URL 을 VERCEL_URL 로 수정
  app/api/auth/[...nextauth]/route.ts
Labels: 버그

#162 fix: nextauth 의 VERCEL_URL 을 VERCEL_PROJECT_PRODUCTION_URL 로 수정
  app/api/auth/[...nextauth]/route.ts
Labels: 버그

#166 fix: kakao redirect protocol 추가
  app/api/auth/[...nextauth]/route.ts
Labels: 버그

#163 Hotfix/env 수정
  .env
  apis/_axiosInstance.ts
  apis/auth.api.ts
  apis/imageUpload.api.ts
  apis/reviews.api.ts
  apis/users.api.ts
  apis/wines.api.ts
  app/api/auth/[...nextauth]/route.ts
  components/auth/ProfileUpload.tsx
  components/auth/UserTapMenu.tsx
  components/modal/AddWineModal.tsx
  components/modal/reviewmodal/AddReviewModal.tsx
  queries/reviews.queries.ts
  queries/users.queries.ts
  queries/wines.queries.ts
  store/useAuthStore.ts
Labels: 버그

#168 fix: svg current 값 미지정 오류 수정
  components/common/Boxes.tsx
Labels: 버그, 수정

#170 fix: team id 변경
  apis/_axiosInstance.ts
  app/(home)/wines/[id]/layout.tsx
Labels: 수정

#176 fix: 리뷰모달 추가
  app/(home)/wines/[id]/components/WineDetail.tsx
  components/wines/NoReviewContent.tsx
Labels: 버그

#177 Feature/167: 목록 페이지 개선 작업
  app/(home)/page.tsx
  components/common/Chip.tsx
  components/common/Header.tsx
  components/common/dropdown/Dropdown.tsx
  components/wines/FilteringModal.tsx
  components/wines/MonthlyWineCard.tsx
  components/wines/MonthlyWineTestCard.tsx
  components/wines/WineCard.tsx
  components/wines/WineCardGallery.tsx
  components/wines/WineSection.tsx
  utils/debounce.ts
Labels: 새 기능, 수정

#179 Fix : mac 크롬 프로필 업로드 오류 해결
  components/auth/ProfileUpload.tsx
Labels: 버그, 수정

#180 fix: Chip 스타일 수정
  components/common/Chip.tsx
Labels: 버그, 수정

#181 fix: Chip 스타일 수정
  components/common/Chip.tsx
Labels: 버그, 수정

#182 fix: 소셜 로그인 api 임시 url 수정
  apis/auth.api.ts
Labels: 버그, 수정

#183 Update README.md
  README.md
Labels: 도큐먼테이션

#185 fix/목록페이지-수정
  app/(home)/page.tsx
  components/common/Chip.tsx
  components/common/Header.tsx
  components/common/dropdown/Dropdown.tsx
  components/wines/FilteringModal.tsx
  components/wines/MonthlyWineCard.tsx
  components/wines/MonthlyWineTestCard.tsx
  components/wines/WineCard.tsx
  components/wines/WineCardGallery.tsx
  components/wines/WineSection.tsx
  utils/debounce.ts
Labels: 수정

#187 Update README.md
  README.md
Labels: 도큐먼테이션

#188 Update README.md
  README.md
Labels: 도큐먼테이션

#189 feat: 구글 adsense 추가
  app/layout.tsx
  utils/script/GoogleAdsense.tsx
Labels: 새 기능

#190 feat: next-sitemap 추가
  next-sitemap.config.js
  package-lock.json
  package.json
Labels: 새 기능
